import { useMemo } from 'react';
import { DashboardNav } from '../components/DashboardNav';
import { useStore } from '../lib/store';
import { buildWeeklyReport } from '../lib/report';
import { HOTEL_NAME } from '../lib/types';

export function WeeklyReport() {
  const { feedback } = useStore();
  const report = useMemo(() => buildWeeklyReport(feedback, HOTEL_NAME), [feedback]);

  const weekOf = new Date().toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });

  return (
    <div className="dashboard">
      <DashboardNav />
      <div className="dash-body">
        <h1 className="dash-title">
          Weekly AI Report <span className="dash-sub">— week of {weekOf}</span>
        </h1>

        <div className="kpi-row">
          <div className="kpi">
            <div className="kpi-label">Responses</div>
            <div className="kpi-value">{report.total}</div>
          </div>
          <div className="kpi">
            <div className="kpi-label">Average Rating</div>
            <div className="kpi-value">
              {report.avg.toFixed(1)} <span className="kpi-star">⭐</span>
            </div>
          </div>
          <div className="kpi positive-kpi">
            <div className="kpi-label">Resolved</div>
            <div className="kpi-value">{report.resolved}</div>
          </div>
          <div className="kpi alert-kpi">
            <div className="kpi-label">Still Open</div>
            <div className="kpi-value">{report.unresolved}</div>
          </div>
        </div>

        <div className="panel ai-report">
          <div className="panel-header">
            <h2>Executive summary</h2>
            <span className="panel-sub">Auto-generated</span>
          </div>
          <p className="ai-report-body">{report.narrative}</p>
          <div className="ai-report-footer">🤖 Generated by GuestPulse AI</div>
        </div>

        <div className="report-cols">
          <div className="panel">
            <div className="panel-header">
              <h2>Highlights</h2>
            </div>
            <ul className="report-list">
              {report.topDepartment && (
                <li>
                  <strong>{report.topDepartment.dept}</strong> is your top performer at{' '}
                  {report.topDepartment.avg.toFixed(1)} ⭐.
                </li>
              )}
              <li>
                {report.resolved} of {report.total} items resolved this week.
              </li>
              {report.themes.length === 0 && <li>No recurring complaints — great week!</li>}
            </ul>
          </div>

          <div className="panel">
            <div className="panel-header">
              <h2>Recurring themes</h2>
              <span className="panel-sub">From negative feedback</span>
            </div>
            {report.themes.length ? (
              <div className="bars">
                {report.themes.map((t) => {
                  const max = report.themes[0].count || 1;
                  return (
                    <div key={t.label} className="bar-row">
                      <div className="bar-label">{t.label}</div>
                      <div className="bar-track">
                        <div
                          className="bar-fill"
                          style={{ width: `${(t.count / max) * 100}%`, background: '#DC2626' }}
                        />
                      </div>
                      <div className="bar-value">{t.count}</div>
                    </div>
                  );
                })}
              </div>
            ) : (
              <p className="panel-sub">No complaints logged this period.</p>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
